In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")
df.head()

,Unnamed: 0,TITLE,LOCATION,PRICE,LAND AREA,ROAD ACCESS,FACING,FLOOR,BEDROOM,BATHROOM,BUILT YEAR,AMENITIES,CITY,LA_N,RA_N,BY_N,PRICE_N
0,0,House for Sale,"Imadol, Lalitpur",Rs. 2.9 Cr,4.0 aana,12 Feet,West,3.0,5.0,4.0,2076 B.S,"['Earthquake Resistant', 'Marbel', 'Parquet', ...",Lalitpur,4.0,12,2076,29000000.0
1,1,House for Sale,"Satdobato, Lalitpur",Rs. 4.75 Cr,3.0 aana,10 Feet,West,4.5,5.0,6.0,2076 B.S,"['Earthquake Resistant', 'Parquet', 'Drinking ...",Lalitpur,3.0,10,2076,47500000.0
2,2,4 BHK House for Sale,"Imadol, Lalitpur",Rs. 1.99 Cr,2.3 aana,10 Feet,West,2.5,4.0,4.0,2060 B.S,"['Earthquake Resistant', 'Marbel', 'Parquet', ...",Lalitpur,2.3,10,2060,19900000.0
3,3,Bungalow House for Sale,"Bhaisepati, Lalitpur",Rs. 4 Cr,7.0 aana,12 Feet,North-West,2.5,4.0,3.0,2059 B.S,"['Earthquake Resistant', 'Marbel', 'Parquet', ...",Lalitpur,7.0,12,2059,40000000.0
4,4,House for Rent,"Maharajgunj, Kathmandu",Rs. 12000000,6.0 aana,20 Feet,South,2.0,4.0,4.0,2071 B.S,"['Earthquake Resistant', 'Parquet', 'Parking',...",Kathmandu,6.0,20,2071,12000000.0